import type { Guide, Screenshot, Step } from '@/core/guides/types';

function blobToBase64(blob: Blob): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => {
      const result = reader.result as string;
      resolve(result.split(',')[1]); // strip data:...;base64, prefix
    };
    reader.onerror = reject;
    reader.readAsDataURL(blob);
  });
}

export async function exportGuideAsHTML(
  guide: Guide,
  steps: Step[],
  screenshots: Map<string, Screenshot>,
): Promise<string> {
  const stepSections: string[] = [];

  for (const step of steps) {
    const screenshot = screenshots.get(step.id);
    let imgHtml = '';
    if (screenshot) {
      const b64 = await blobToBase64(screenshot.blob);
      imgHtml = `<img src="data:${screenshot.mimeType};base64,${b64}" alt="Step ${step.index + 1}" style="max-width:100%;border-radius:8px;margin:12px 0;" />`;
    }
    stepSections.push(`
      <div style="margin-bottom:32px;">
        <div style="display:flex;align-items:center;gap:8px;margin-bottom:8px;">
          <span style="display:inline-flex;align-items:center;justify-content:center;width:28px;height:28px;border-radius:50%;background:#2563eb;color:#fff;font-size:14px;font-weight:bold;">${step.index + 1}</span>
          <p style="margin:0;font-size:16px;">${escapeHtml(step.description)}</p>
        </div>
        ${imgHtml}
      </div>`);
  }

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(guide.title)}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 800px; margin: 0 auto; padding: 24px; color: #1f2937; }
    h1 { font-size: 24px; margin-bottom: 8px; }
    .meta { font-size: 12px; color: #6b7280; margin-bottom: 24px; }
  </style>
</head>
<body>
  <h1>${escapeHtml(guide.title)}</h1>
  <p class="meta">${steps.length} steps &middot; Created ${new Date(guide.createdAt).toLocaleDateString()}</p>
  ${stepSections.join('\n')}
  <footer style="margin-top:48px;padding-top:16px;border-top:1px solid #e5e7eb;font-size:11px;color:#9ca3af;">Generated by Mimik</footer>
</body>
</html>`;
}

function escapeHtml(text: string): string {
  return text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}
