import type { Guide, Screenshot, Step } from '@/core/guides/types';

function blobToBase64(blob: Blob): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => {
      const result = reader.result as string;
      resolve(result.split(',')[1]);
    };
    reader.onerror = reject;
    reader.readAsDataURL(blob);
  });
}

export async function exportGuideAsMarkdown(
  guide: Guide,
  steps: Step[],
  screenshots: Map<string, Screenshot>,
): Promise<string> {
  const lines: string[] = [
    `# ${guide.title}`,
    '',
    `*${steps.length} steps — Created ${new Date(guide.createdAt).toLocaleDateString()}*`,
    '',
  ];

  for (const step of steps) {
    lines.push(`## Step ${step.index + 1}: ${step.description}`);
    lines.push('');
    const screenshot = screenshots.get(step.id);
    if (screenshot) {
      const b64 = await blobToBase64(screenshot.blob);
      lines.push(`![Step ${step.index + 1}](data:${screenshot.mimeType};base64,${b64})`);
      lines.push('');
    }
  }

  lines.push('---');
  lines.push('*Generated by Mimik*');
  return lines.join('\n');
}
