import { jsPDF } from 'jspdf';
import type { Guide, Screenshot, Step } from '@/core/guides/types';
import { logger } from '@/lib/logger';

function blobToDataUrl(blob: Blob): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(reader.result as string);
    reader.onerror = reject;
    reader.readAsDataURL(blob);
  });
}

export async function exportGuideAsPDF(
  guide: Guide,
  steps: Step[],
  screenshots: Map<string, Screenshot>,
): Promise<Blob> {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text(guide.title, margin, y + 7);
  y += 14;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(107, 114, 128);
  doc.text(`${steps.length} steps — Created ${new Date(guide.createdAt).toLocaleDateString()}`, margin, y);
  doc.setTextColor(0, 0, 0);
  y += 10;

  for (const step of steps) {
    if (y > doc.internal.pageSize.getHeight() - 60) {
      doc.addPage();
      y = margin;
    }

    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text(`${step.index + 1}.`, margin, y + 4);
    doc.setFont('helvetica', 'normal');
    const descLines = doc.splitTextToSize(step.description, contentWidth - 10);
    doc.text(descLines, margin + 8, y + 4);
    y += descLines.length * 5 + 4;

    const screenshot = screenshots.get(step.id);
    if (screenshot) {
      try {
        const dataUrl = await blobToDataUrl(screenshot.blob);
        const imgWidth = contentWidth;
        const imgHeight = (screenshot.height / screenshot.width) * imgWidth;
        const maxImgHeight = 100; // mm — cap height to prevent single image filling entire page
        const finalHeight = Math.min(imgHeight, maxImgHeight);

        if (y + finalHeight > doc.internal.pageSize.getHeight() - margin) {
          doc.addPage();
          y = margin;
        }

        doc.addImage(dataUrl, 'JPEG', margin, y, imgWidth, finalHeight);
        y += finalHeight + 8;
      } catch (err) {
        logger.warn(' PDF: failed to embed screenshot for step', step.index, err);
        y += 4;
      }
    }

    y += 4; // spacing between steps
  }

  doc.setFontSize(8);
  doc.setTextColor(156, 163, 175);
  doc.text('Generated by Mimik', margin, doc.internal.pageSize.getHeight() - 8);

  return doc.output('blob');
}
